import Head from 'next/head'
import { Experiences } from '../components/Experiences'
import Hero from '../components/Hero'
import { Navbar } from '../components/Navbar'
import ProjectDetail from '../components/ProjectDetail'
import Skills from '../components/Skills'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Risa | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Experiences/>
      <Skills/>
      <ProjectDetail />
    </div>
  )
}
